[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-replica-node"
description = "Solana replication node"
version = "1.13.5"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-validator"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
rand = "0.7.0"
solana-clap-utils = { path = "../clap-utils", version = "=1.13.5" }
solana-client = { path = "../client", version = "=1.13.5" }
solana-download-utils = { path = "../download-utils", version = "=1.13.5" }
solana-genesis-utils = { path = "../genesis-utils", version = "=1.13.5" }
solana-gossip = { path = "../gossip", version = "=1.13.5" }
solana-ledger = { path = "../ledger", version = "=1.13.5" }
solana-logger = { path = "../logger", version = "=1.13.5" }
solana-net-utils = { path = "../net-utils", version = "=1.13.5" }
solana-replica-lib = { path = "../replica-lib", version = "=1.13.5" }
solana-rpc = { path = "../rpc", version = "=1.13.5" }
solana-runtime = { path = "../runtime", version = "=1.13.5" }
solana-sdk = { path = "../sdk", version = "=1.13.5" }
solana-send-transaction-service = { path = "../send-transaction-service", version = "=1.13.5" }
solana-streamer = { path = "../streamer", version = "=1.13.5" }
solana-validator = { path = "../validator", version = "=1.13.5" }
solana-version = { path = "../version", version = "=1.13.5" }

[dev-dependencies]
serial_test = "0.6.0"
solana-core = { path = "../core", version = "=1.13.5" }
solana-local-cluster = { path = "../local-cluster", version = "=1.13.5" }
tempfile = "3.3.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.7.0"
